version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: io.reactivex.rxjava3:rxjava
    versions:
    - 3.0.11
    - 3.0.9
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.32
  - dependency-name: com.google.firebase:firebase-crashlytics
    versions:
    - 17.4.0
  - dependency-name: androidx.navigation:navigation-ui-ktx
    versions:
    - 2.3.4
  - dependency-name: androidx.navigation:navigation-fragment-ktx
    versions:
    - 2.3.4
  - dependency-name: androidx.navigation:navigation-ui
    versions:
    - 2.3.4
  - dependency-name: androidx.navigation:navigation-fragment
    versions:
    - 2.3.4
  - dependency-name: com.google.firebase:firebase-firestore-ktx
    versions:
    - 22.0.2
    - 22.1.0
  - dependency-name: com.google.firebase:firebase-crashlytics-gradle
    versions:
    - 2.4.1
    - 2.5.0
  - dependency-name: com.google.firebase:firebase-auth
    versions:
    - 20.0.2
